### ISSUE TITLE
issue with shaders

### ISSUE THREAD

**Issue by PabloDnSS** [afoxxvi/AsteorBarMod#1]
awesome mod i really want to use it but i have issues with complementary shaders

![2024-03-21_16 58 45](https://github.com/afoxxvi/AsteorBarMod/assets/161372702/e5fad24f-3893-4f79-84ea-30261b103330)

**Comment by afoxxvi** [comment]
Sorry for late response, could you please tell more info like mod loader and mc version?
By the way, I'm currently making a new version of mod, and has made some change in rendering, and here's in game screenshot:
<img width="418" alt="Snipaste_2024-03-25_16-02-45" src="https://github.com/afoxxvi/AsteorBarMod/assets/31498980/3b347cfa-bec0-427e-b0f3-813e32afa9f9">
I'm using mc 1.19.4, ComplementaryUnbound_r5.1.1, and I wonder do you think this is with good enough look?

**Comment by PabloDnSS** [comment]
Im using forge on 1.20.1 with complementary reimagined+euphoria patches

really nice maybe more color or less transparency to be more visible when the bar has the sky as background

**Comment by afoxxvi** [comment]
That is easy, I will add a global alpha config entry allowing you to control the bar's transparency in the next version, which won't be released later than April 1st.

**Comment by afoxxvi** [comment]
@PabloDnSS Hello, I'm willing to get your feedback, is rendering works well now?

**Comment by PabloDnSS** [comment]
and some bars are blinking when standing still thirst and hunger

**Comment by afoxxvi** [comment]
it's strange, have you tried with some other health bar mods such as Neat?

**Comment by PabloDnSS** [comment]
No problem with neat

**Comment by afoxxvi** [comment]
Were you using Oculus to use shader? I couldn't reproduce it in Optifine, and another recent feedback reproduced this issue with Oculus, I may continue to find a solution.

**Comment by afoxxvi** [comment]
Hello, please try with this release: https://github.com/afoxxvi/AsteorBarMod/releases/tag/1.4.6-dev1
