### ISSUE TITLE
Issue with compatibility with Appleskin on 1.20.6

### ISSUE THREAD

**Issue by Boetacular100** [afoxxvi/AsteorBarMod#12]
I think what is going on is that the mod will crash when I load into a world and I have Appleskin enabled, along with the AsteorBar HUD bars enabled. When I disable the HUD bars, it completely hides my HUD in survival mode, meaning I can't see my health, my experience levels, and my hunger.
When I disable AsteorBar HUD, join a world, and then enable it, it works fine. If it is enabled when I join a world, the whole game crashes.
Here are some logs from last time this happened.
[crash-2024-05-27_18.35.05-client.txt](https://github.com/afoxxvi/AsteorBarMod/files/15462927/crash-2024-05-27_18.35.05-client.txt)
[hs_err_pid18196.log](https://github.com/afoxxvi/AsteorBarMod/files/15462928/hs_err_pid18196.log)

The only reason I wanted this mod is because I wanted the mob health bars, but if I only want that and disable the HUD, I can't see the regular HUD.

**Comment by afoxxvi** [comment]
Should be fixed in v1.4.5.1, and thanks for detailed feedback.
