### ISSUE TITLE
LightShield模组更新后联动失效

### ISSUE THREAD

**Issue by RhyVis** [afoxxvi/AsteorBarMod#2]
你好，联动列表里面的[LightShield](https://www.mcmod.cn/class/13967.html)模组在这两天更新版本后，联动似乎挂掉了，表现为护盾图标仍以原版方式渲染，不受这个UI模组以及F8换预设的调整。

**Comment by afoxxvi** [comment]
因为其发布晚于模组1.4.1版本的开发，对当时未适配1.20.1版本的模组进行兼容是不现实的。1.4.1.1版本已跟进兼容。
