### ISSUE TITLE
Cannot connect to NeoForge server, mod version 1.21.1

### ISSUE THREAD

**Issue by PacifistMage** [afoxxvi/AsteorBarMod#20]
![image](https://github.com/user-attachments/assets/71a13bdd-dad7-4a86-9af2-bba7029661b1)

I'm having a problem with the AsteorBar mod. I've attached a screenshot of the error message I'm getting. Any help or guidance would be greatly appreciated. Thank you.

**Comment by afoxxvi** [comment]
Do you have tried installing this mod on server side?

**Comment by PacifistMage** [comment]
Will update again once I've done it. 👍

**Comment by PacifistMage** [comment]
![image](https://github.com/user-attachments/assets/90849af9-ef98-40c6-aa18-0f57a595760d)

I thought this mod was just for the client-side only, my bad. I appreciate your help anyway.

**Comment by afoxxvi** [comment]
Honestly speaking this should not happen though, since the server side was designed to be 'optional', but now acts as 'required', I may fix this if any solution found, and glad to see you're no longer bothered by this.
