### ISSUE TITLE
Can't Connect to NeoForge Server

### ISSUE THREAD

**Issue by StygianEmperor** [afoxxvi/AsteorBarMod#3]
I can't seem to connect to my NeoForge server while running this mod. It gives the "Incompatible Client" error screen, and lists 5 Channel names - asteorbar:tough_as_nails, asteorbar:entity_absorption, asteorbar:saturation, asteorbar:exhaustion, asteorbar:activate

Each channel has the description "This channel is missing on the server side, but required on the client!"

Adding this mod to the server instead gives an internal server error, I'll include the latest log: 
[latest.log](https://github.com/afoxxvi/AsteorBarMod/files/14968966/latest.log)

Let me know if I screwed up somewhere.

**Comment by afoxxvi** [comment]
Thanks for your detailed information.
This mod was not designed for mod server at first, and then the error was caused, I will try to fix it.

**Comment by afoxxvi** [comment]
[asteorbar-neoforge-1.20.4-1.4.3.zip](https://github.com/afoxxvi/AsteorBarMod/files/14969580/asteorbar-neoforge-1.20.4-1.4.3.zip)
here's a simple fix, please try with this file, don't forget to uncompress the zip file.

**Comment by StygianEmperor** [comment]
> [asteorbar-neoforge-1.20.4-1.4.3.zip](https://github.com/afoxxvi/AsteorBarMod/files/14969580/asteorbar-neoforge-1.20.4-1.4.3.zip) here's a simple fix, please try with this file, don't forget to uncompress the zip file.

This seems to work, thanks!
