### ISSUE TITLE
A few mod compats for ya

### ISSUE THREAD

**Issue by emorydeer2** [afoxxvi/AsteorBarMod#4]
https://modrinth.com/mod/botania (the mana bar, they're called the same thing 🤷)
https://modrinth.com/mod/ars-nouveau (the mana bar)
https://modrinth.com/mod/create & https://modrinth.com/mod/create-fabric (the air meter, though it is just a number, i'd also suggest, instead of making a separate bar, integrating it with the vanilla oxygen meter, like saturation)
https://modrinth.com/mod/origins (the resource bar)
~~https://modrinth.com/mod/speedometer (the speedometer)~~
~~https://modrinth.com/mod/improved-mobs (the difficulty number)~~
~~https://modrinth.com/mod/sanity-descent-into-madness (the sanity meter)~~

**Comment by afoxxvi** [comment]
Added to todo list, hope they do have stable API. compatibility work should last several weeks since they are much more complicated to test, and I'm currently focusing on other development tasks.
An additional question, since I'm not familiar with all these mods, could you pls tell how can I see their bars?

**Comment by emorydeer2** [comment]
- Speedometer's speedometer shows constantly in-game, changes while moving
- Ars's Mana bar shows when you're holding a spellbook or when you use a spell, or anything about your mana changes
- Botania's mana bar shows when you have a mana tablet or are wearing a band of mana, & are using mana, or your mana decreases
- Origins' resource bar is pretty complicated, since it depends on the origin itself, I'd suggest just asking the dev (eggohito) how it works so you can add compatibility. [Their Discord server](https://discord.gg/VdGgwXwWNa)
- - A very run-down explanation is that Origins' origins can show a resource bar with a "power", defined & changed by the origin, based on factors determined by the origin.
- Improved Mobs' difficulty number shows constantly in-game, and changes every day by an amount defined by the config
- Sanity: DIM's sanity meter is a brain icon which shows constantly in-game, and decreases depending on actions defined by the mod & its config. A number can be shown with a client config option.

While writing this also just remembered that Create has a timer for its backtanks, which a number shown while in water/while it's decreasing.

**Comment by afoxxvi** [comment]
Thank you for providing such detailed information, I'll do further work later.

**Comment by afoxxvi** [comment]
Compatibility works of Ars Nouveau and Botania is done, while speedometer, improved-mobs and sanity doesn't seems have to be rendered as a bar for they just provides a small screen component.
As for Origins, I may not fully understand their code so unluckily, compatability work will be delayed for long.
I'm sorry for this, and really appreciate for your effort.

**Comment by emorydeer2** [comment]
That's absolutely okay! Botania & Ars' bars are the most necessary to know, as running out can mean immediate death in many cases. And I'm fairly surprised you can at all integrate with Origins, though I would suggest some sort of temporary patch to move it out of the way.

**Comment by afoxxvi** [comment]
The next release should not be soon, so if you do wish to use it earlier, you can provide a specific mc version and mod loader, and I will provide a dev version for you.
Also, I do think a seperate todo list issue should be good.

**Comment by emorydeer2** [comment]
Oh, ok, then I need Fabric 1.20.1 soonest, & I'll make that issue for you.

**Comment by afoxxvi** [comment]
Since I found that Origin itself doesn't do render, it was Apoli(one of its depencendies but not found in jar) instead, compatibility work is easy now.
Here's the pre-release:
https://github.com/afoxxvi/AsteorBarMod/releases/tag/1.4.6-dev1
