### ISSUE TITLE
Bug With Retro Damage Indicators

### ISSUE THREAD

**Issue by Danmccool** [afoxxvi/AsteorBarMod#6]
Look At The Health Bar In The Screenshots

![Screenshot 2024-04-26 190449](https://github.com/afoxxvi/AsteorBarMod/assets/121473014/4e4d2291-9a83-43cd-93e2-eaf01daed9e6)
![Screenshot 2024-04-26 190440](https://github.com/afoxxvi/AsteorBarMod/assets/121473014/2b09bb0c-9464-46bd-8a2f-1f1df8947018)

**Comment by afoxxvi** [comment]
I have no permission to view it, and pls attach image files in the editor, or u may use imgur instead.

**Comment by Danmccool** [comment]
I Attached The images In My Post Take A Look

**Comment by Danmccool** [comment]
@afoxxvi I Attached The Images

**Comment by afoxxvi** [comment]
I have noticed it, however I've also been focusing on my other tasks for weeks, and will back to fix this when I'm free, sorry for that and thanks for your understanding.

**Comment by Danmccool** [comment]
Ok

**Comment by afoxxvi** [comment]
Update another mod when they accepted my update. I have already tested it and should work correctly now.

**Comment by Danmccool** [comment]
Sounds Good

**Comment by Danmccool** [comment]
@afoxxvi Can You Send me The Jar For You Fork of Retro Damage Indcators

**Comment by afoxxvi** [comment]
[unzip this.zip](https://github.com/afoxxvi/AsteorBarMod/files/15446020/unzip.this.zip)
